version: '3.8'
services:

  postgis:
    container_name: advanced_web_mapping_postgis
    image: kartoza/postgis
    volumes:
      - postgresdb:/var/lib/postgresql
    env_file:
      - 'postgres.env'
    networks:
      - backend
    ports:
      - "25432:5432"

  pgadmin:
    container_name: advanced_web_mapping_pgadmin
    image: dpage/pgadmin4
    volumes:
      - pgadmin:/var/lib/pgadmin
    env_file:
      - 'pgadmin.env'
    ports:
      - "8000:8000"
    networks:
      - backend

  nginx:
    container_name: advanced_web_mapping_nginx
    build:
      context: ../
      dockerfile: ./docker/nginx/Dockerfile
    networks:
      - backend
    ports:
      - "80:80"

  django:
    container_name: advanced_web_mapping_django
    build:
      context: ../
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - "8001:8001"
    env_file:
      - 'django.env'

networks:
  backend:

volumes:
  postgresdb:
  pgadmin: